import './pieces.js';
import './board.js';
import './engine.js';
import './chess-core.js';
import './app-dialog.js';
import './boost.js';
import './header.js';
import './footer.js';
import './app.js';